// ===== ダミーデータ：食肉卸 EC（朝の整理ダッシュボード）=====

const STAGES = ["受注", "製造", "梱包", "発送", "完了"];

const initialOrders = [
  {
    id: "ORD-2841",
    customer: "中華料理 紅蘭",
    customerType: "業務用",
    receivedAt: "02:14",
    receivedLabel: "深夜2時",
    items: [
      { name: "黒毛和牛 すき焼き用 ロース", qty: "3kg" },
      { name: "牛丼用 切り落とし", qty: "5kg" },
    ],
    totalYen: 48600,
    stage: "受注",
    priority: "high",
    deliveryDate: "明日 12:00 厳守",
    leadTimeTight: true,
    needsCustomerQuestion: true,
    customerQuestion: "脂の量（多め/普通/控えめ）の指定がないため確認が必要",
    notes: [
      "前回ご注文時「脂は控えめ」とのコメントあり",
      "明日のランチ営業向け — 製造を朝イチ着手で間に合う",
    ],
    flags: ["短納期", "顧客確認"],
  },
  {
    id: "ORD-2842",
    customer: "山田 美咲 様",
    customerType: "個人",
    receivedAt: "23:47",
    receivedLabel: "昨夜",
    items: [
      { name: "BBQ満腹セット 4〜5人前", qty: "1セット" },
      { name: "牛タン厚切り 塩仕込み", qty: "500g" },
    ],
    totalYen: 12800,
    stage: "受注",
    priority: "high",
    deliveryDate: "今週土曜 午前指定",
    leadTimeTight: false,
    needsCustomerQuestion: false,
    notes: ["BBQ 6/6（土）— 余裕あり", "リピーター 8回目"],
    flags: [],
  },
  {
    id: "ORD-2843",
    customer: "焼肉 炎 浜松町店",
    customerType: "業務用",
    receivedAt: "01:08",
    receivedLabel: "深夜1時",
    items: [
      { name: "和牛カルビ 業務用", qty: "10kg" },
      { name: "ハラミ 業務用", qty: "8kg" },
      { name: "牛ホルモン MIX", qty: "5kg" },
    ],
    totalYen: 158400,
    stage: "受注",
    priority: "med",
    deliveryDate: "金曜 朝9:00 着",
    leadTimeTight: false,
    notes: ["定期顧客 / 月8回前後", "請求書払い"],
    flags: ["大口"],
  },
  {
    id: "ORD-2839",
    customer: "居酒屋 縁",
    customerType: "業務用",
    receivedAt: "21:32",
    receivedLabel: "昨夜",
    items: [
      { name: "黒毛和牛 ステーキ用 サーロイン 200g×10", qty: "2kg" },
    ],
    totalYen: 36000,
    stage: "製造",
    priority: "high",
    deliveryDate: "明日 16:00 着",
    leadTimeTight: true,
    notes: ["カット中（担当：佐藤）"],
    flags: ["短納期"],
  },
  {
    id: "ORD-2837",
    customer: "佐藤 健一 様",
    customerType: "個人",
    receivedAt: "20:11",
    receivedLabel: "昨夜",
    items: [
      { name: "お肉の福袋 プレミアム", qty: "1袋" },
    ],
    totalYen: 9800,
    stage: "製造",
    priority: "low",
    deliveryDate: "今週中",
    leadTimeTight: false,
    notes: [],
    flags: [],
  },
  {
    id: "ORD-2835",
    customer: "鈴木 真理 様",
    customerType: "個人",
    receivedAt: "昨日 18:42",
    receivedLabel: "昨日",
    items: [
      { name: "手作りコロッケ 20個", qty: "20個" },
      { name: "黒豚メンチカツ 12個", qty: "12個" },
    ],
    totalYen: 4860,
    stage: "梱包",
    priority: "med",
    deliveryDate: "明日 午後",
    leadTimeTight: false,
    notes: ["冷凍便"],
    flags: [],
  },
  {
    id: "ORD-2834",
    customer: "ステーキハウス 牡丹",
    customerType: "業務用",
    receivedAt: "昨日 15:20",
    receivedLabel: "昨日",
    items: [
      { name: "黒毛和牛 シャトーブリアン", qty: "1.2kg" },
    ],
    totalYen: 68400,
    stage: "梱包",
    priority: "high",
    deliveryDate: "今日 16:00 着",
    leadTimeTight: true,
    notes: ["保冷剤多めで指定"],
    flags: ["要冷蔵", "本日着"],
  },
  {
    id: "ORD-2828",
    customer: "焼肉 炎 浜松町店",
    customerType: "業務用",
    receivedAt: "昨日 11:00",
    receivedLabel: "昨日",
    items: [
      { name: "牛タン厚切り", qty: "3kg" },
      { name: "ハラミ", qty: "5kg" },
    ],
    totalYen: 52800,
    stage: "発送",
    priority: "med",
    deliveryDate: "今日 18:00 着予定",
    leadTimeTight: false,
    notes: ["ヤマト 伝票 4521-8870-1129"],
    flags: ["追跡可能"],
  },
  {
    id: "ORD-2820",
    customer: "餃子の田中 様",
    customerType: "個人",
    receivedAt: "一昨日",
    receivedLabel: "完了",
    items: [
      { name: "手作り餃子 50個", qty: "50個" },
    ],
    totalYen: 3200,
    stage: "完了",
    priority: "low",
    deliveryDate: "配達済",
    leadTimeTight: false,
    notes: [],
    flags: [],
  },
];

const initialInquiries = [
  {
    id: "INQ-512",
    customer: "ステーキハウス 牡丹",
    customerType: "業務用",
    receivedAt: "03:47",
    type: "クレーム",
    angerLevel: 3,
    subject: "本日着の和牛、サシの入りが画像と異なる",
    preview: "先日のシャトーブリアン、届いた品が画像と明らかに違う。今日のディナー営業に間に合わないと困る。至急折り返し電話を希望。",
    status: "未対応",
    needsSupplierContact: false,
    relatedOrder: "ORD-2810",
    suggestedReply: "至急お電話差し上げ、現品の写真を確認のうえ、本日中の差替え便を手配します。",
    tags: ["要電話折返", "本日対応"],
  },
  {
    id: "INQ-511",
    customer: "井上 雅人 様",
    customerType: "個人",
    receivedAt: "01:22",
    type: "型番違い",
    angerLevel: 2,
    subject: "注文したのは『すき焼き用ロース』だが『切り落とし』が届いた",
    preview: "土曜のすき焼きパーティー用に頼んだのにこれでは…。交換は可能でしょうか？",
    status: "未対応",
    needsSupplierContact: false,
    relatedOrder: "ORD-2812",
    suggestedReply: "誤出荷をお詫び。本日中にロース 600g を再発送、切り落としはそのままお納めいただく案内。",
    tags: ["誤出荷", "再発送"],
  },
  {
    id: "INQ-510",
    customer: "BBQパーク多摩",
    customerType: "業務用",
    receivedAt: "00:51",
    type: "メーカー確認要",
    angerLevel: 1,
    subject: "BBQセットの牛タン、産地を米国産から国産に変更できるか",
    preview: "週末イベント向け。仕入先に在庫があれば差額負担で変更したい。",
    status: "未対応",
    needsSupplierContact: true,
    supplier: "(株)タナカ食肉",
    relatedOrder: "ORD-2815",
    suggestedReply: "仕入先タナカ食肉に在庫確認 → 差額見積を本日中に提示。",
    tags: ["仕入先確認"],
  },
  {
    id: "INQ-509",
    customer: "和田 千鶴 様",
    customerType: "個人",
    receivedAt: "23:18",
    type: "色違い",
    angerLevel: 2,
    subject: "ホルモンMIX、写真より色が黒っぽい",
    preview: "写真と違い黒っぽい部分が多い。鮮度に問題ないか確認したい。",
    status: "対応中",
    needsSupplierContact: false,
    relatedOrder: "ORD-2814",
    suggestedReply: "鮮度に問題なし（処理直後の色味）と説明資料添付。返金不要・次回クーポン提供を提案。",
    tags: ["商品説明"],
  },
  {
    id: "INQ-508",
    customer: "中華料理 紅蘭",
    customerType: "業務用",
    receivedAt: "22:04",
    type: "配送",
    angerLevel: 1,
    subject: "配達時間の指定を14時 → 11時に変更できるか",
    preview: "明日のランチ営業に間に合わせたい。",
    status: "未対応",
    needsSupplierContact: false,
    relatedOrder: "ORD-2841",
    suggestedReply: "配送業者に変更依頼。可否確認のうえ折返し。",
    tags: ["配送変更"],
  },
  {
    id: "INQ-506",
    customer: "高橋 浩二 様",
    customerType: "個人",
    receivedAt: "昨日 19:10",
    type: "その他",
    angerLevel: 1,
    subject: "餃子のタレは付属していますか",
    preview: "プレゼント用に検討中です。",
    status: "完了",
    needsSupplierContact: false,
    suggestedReply: "別売り。タレ付きセットの案内。",
    tags: [],
  },
];

const initialTasks = [
  { id: "T1", title: "ORD-2841（紅蘭）— 脂の量を顧客に確認", category: "顧客確認", priority: "high", done: false, dueBy: "9:00", linkedTo: "ORD-2841" },
  { id: "T2", title: "INQ-512（牡丹）— 折返し電話 → 差替便手配", category: "問い合わせ", priority: "high", done: false, dueBy: "9:30", linkedTo: "INQ-512" },
  { id: "T3", title: "INQ-510 — タナカ食肉に国産牛タン在庫を確認", category: "仕入先確認", priority: "med", done: false, dueBy: "11:00", linkedTo: "INQ-510" },
  { id: "T4", title: "ORD-2843（焼肉炎）— 仕入計画に組み込み", category: "発注", priority: "med", done: false, dueBy: "12:00", linkedTo: "ORD-2843" },
  { id: "T5", title: "ORD-2834 — 本日着、保冷剤多めで梱包指示", category: "梱包", priority: "high", done: true, dueBy: "10:00", linkedTo: "ORD-2834" },
  { id: "T6", title: "INQ-511 — ロース600g 再発送伝票発行", category: "問い合わせ", priority: "high", done: false, dueBy: "10:30", linkedTo: "INQ-511" },
  { id: "T7", title: "ORD-2839（縁）— カット完了確認 → 梱包へ", category: "製造", priority: "med", done: false, dueBy: "13:00", linkedTo: "ORD-2839" },
  { id: "T8", title: "今週末 BBQセット 仕入数量レビュー", category: "発注", priority: "low", done: false, dueBy: "15:00", linkedTo: null },
  { id: "T9", title: "コロッケ 翌週分の製造計画", category: "製造", priority: "low", done: true, dueBy: "—", linkedTo: null },
];

Object.assign(window, {
  STAGES,
  initialOrders,
  initialInquiries,
  initialTasks,
});
